version: 2.1

# orbs:
#   win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    working_directory: ~/gitsrc
    docker:
      - image: circleci/node:jessie-browsers
    environment:
      JVM_OPTS: -Xmx3200m
      NODE_ENV: false
      COVERALLS_REPO_TOKEN: HICc0XwxeBruKFxp0BdCKfGLIHGGTYQhg
    steps:
      - checkout
      - run:
          name: Install Chrome
          command: $Path = $env:TEMP; $Installer = "chrome_installer.exe"; Invoke-WebRequest "http://dl.google.com/chrome/install/375.126/chrome_installer.exe" -OutFile $Path\$Installer; Start-Process -FilePath $Path\$Installer -Args "/silent /install" -Verb RunAs -Wait; Remove-Item $Path\$Installer
          shell: powershell.exe
      - run:
          name: setup-for-karma
          command: npm set prefix=/home/circleci/npm && echo 'export PATH=$HOME/circleci/npm/bin:$PATH' >> /home/circleci/.bashrc
          # shell: bash.exe
      - run:
          name: globals karma-cli, jasmine, jspm
          command: npm install -g karma-cli jasmine jspm
          # shell: cmd.exe
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
          # shell: cmd.exe
      - run:
          name: run test
          command: npm run testc
          # shell: cmd.exe
      - store_artifacts:
          path: coverage
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - .node_modules
